[build]
  command = "jekyll build"
  publish = "_site"

[context.production.environment]
  JEKYLL_ENV = "production"

[context.deploy-preview]
  command = "jekyll build"
  publish = "_site"

[context.branch-deploy]
  command = "jekyll build"
  publish = "_site"

[context.next.environment]
  JEKYLL_ENV = "development"
